const Best = [
  {
    id: 1,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635029952/Book%20Home/Books/Best%20Selling/The-Illustrated-a-Brief-History-of-Time-9780553103748_lhotvg.jpg',
    Title: 'A Brief History of Time',
    Author: 'Stephen Hawking',
    Price: '21.55',
    OldPrice: '$25.0',
    AuthorLink: 'jhcdhchuc',
    Link: 'huhuh',
  },
  {
    id: 2,
    Image: 'https://res.cloudinary.com/osaz/image/upload/v1635029991/Book%20Home/Books/Best%20Selling/The-Book-of-Night-Women-9781594488573_eyc4g9.jpg',
    Title: 'The Book of Night Women',
    Author: 'Marlon James',
    Price: '20.00',
    AuthorLink: 'jkki',
    Link: 'iukiuu',
  },
    {
    id: 3,
    Image: 'https://res.cloudinary.com/osaz/image/upload/v1635030176/Book%20Home/Books/Best%20Selling/Big-Week-The-Biggest-Air-Battle-of-World-War-II-by-James-Holland-300x456_g3meou.jpg',
    Title: 'The Biggest Air Battle of WWII',
    Author: 'James Holland',
    Price: '30.00',
    OldPrice: '$35.43',
    AuthorLink: 'rfr',
    Link: 'ffr',
  },
   {
    id: 4,
    Image: 'https://res.cloudinary.com/osaz/image/upload/v1635029646/Book%20Home/Books/Best%20Selling/Waiting-for-Eden-A-novel-by-Elliot-Ackerman-300x456_pc7sqo.jpg',
    Title: 'Waiting for Eden: A Novel',
    Author: 'ELLIOT ACKERMAN',
    Price: '10.34',
    AuthorLink: 'rff',
    Link: 'rfrff',
  },
  {
    id: 5,
    Image: 'https://res.cloudinary.com/osaz/image/upload/v1635029652/Book%20Home/Books/Best%20Selling/Food-of-the-Italian-South-by-Katie-Parla-300x456_wwdxqx.jpg',
    Title: 'Food of the Italian South',
    Author: 'KATIE PARLA',
    Price: '10.45',
    AuthorLink: 'dede',
    Link: 'edeed',
  },
  {
    id: 6,
    Image: 'https://res.cloudinary.com/osaz/image/upload/v1635029663/Book%20Home/Books/Best%20Selling/Spy-A-Novel-by-Danielle-Steeel-300x456_ohnyld.jpg',
    Title: 'Spy: A Novel',
    Author: 'DANIELLE STEEL',
    Price: '20.00',
    AuthorLink: 'dcdc',
    Link: 'ecd',
  },
  {
    id: 7,
    Image: 'https://res.cloudinary.com/osaz/image/upload/v1635030107/Book%20Home/Books/Best%20Selling/A-Lily-in-the-Light-by-Kristin-Fields-300x456_otemst.jpg',
    Title: 'A Lily in the Light',
    Author: 'KRISTIN FIELDS',
    Price: '34.00',
    AuthorLink: 'sddsdsc',
    Link: 'rfecc',
  },
  {
    id: 8,
    Image: 'https://res.cloudinary.com/osaz/image/upload/v1635029842/Book%20Home/Books/Best%20Selling/Invisible-Man-Ellison-Ralph-9780141184425_qkmafn.jpg',
    Title: 'Invicible Man',
    Author: 'Elison Ralph',
    Price: '24.65',
    AuthorLink: 'fbbg',
    Link: 'hghgbg',
  },
  {
    id: 9,
    Image: 'https://res.cloudinary.com/osaz/image/upload/v1635029643/Book%20Home/Books/Best%20Selling/2-Rules-for-Life-An-Antidote-to-Chaos-by-Jordan-B.-Peterson-300x456_lnpopl.jpg',
    Title: '12 Rules for Life: An Antidote to Chaos',
    Author: 'JORDAN B. PETERSON',
    Price: '12.43',
    AuthorLink: 'tytut',
    Link: 'ryuyu',
  },
  {
    id: 10,
    Image: 'https://res.cloudinary.com/osaz/image/upload/v1635029900/Book%20Home/Books/Best%20Selling/9780425284704_ox2vhb.jpg',
    Title: 'When We Were Yours',
    Author: 'Lisa Wingate',
    Price: '10.00',
    OldPrice: '$12.98',
    AuthorLink: 'rfrf',
    Link: 'rfcdc',
  },
]

export default Best
