const Data = [
  {
    id: 1,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635029952/Book%20Home/Books/Best%20Selling/The-Illustrated-a-Brief-History-of-Time-9780553103748_lhotvg.jpg',
    Title: 'A Brief History of Time',
    Author: 'Stephen Hawking',
    Price: '21.55',
    OldPrice: '$25.0',
    AuthorLink: 'stephen-hawking',
    Links: 'A-Brief-History-of-Time',
    Publisher: 'Bantam',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 212,
    Year: 1998,
    Language: 'English',
  },
  {
    id: 2,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635029991/Book%20Home/Books/Best%20Selling/The-Book-of-Night-Women-9781594488573_eyc4g9.jpg',
    Title: 'The Book of Night Women',
    Author: 'Marlon James',
    Price: '20.00',
    AuthorLink: 'marlon-james',
    Links: 'The-Book-of-Night-Women',
    Publisher: 'Penguin',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 427,
    Year: 2010,
    Language: 'English',
  },
  {
    id: 3,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635030176/Book%20Home/Books/Best%20Selling/Big-Week-The-Biggest-Air-Battle-of-World-War-II-by-James-Holland-300x456_g3meou.jpg',
    Title: 'The Biggest Air Battle of WWII',
    Author: 'James Holland',
    Price: '30.00',
    OldPrice: '$35.43',
    AuthorLink: 'james-holland',
    Links: 'The-Biggest-Air-Battle-of-WWII',
    Publisher: 'Atlantic Monthly Press',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 400,
    Year: 2018,
    Language: 'English',
  },
  {
    id: 4,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635029646/Book%20Home/Books/Best%20Selling/Waiting-for-Eden-A-novel-by-Elliot-Ackerman-300x456_pc7sqo.jpg',
    Title: 'Waiting for Eden: A Novel',
    Author: 'ELLIOT ACKERMAN',
    Price: '10.34',
    AuthorLink: 'elliot-ackerman',
    Links: 'Waiting-for-Eden:-A-Novel',
    Publisher: 'Knopf',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 192,
    Year: 2018,
    Language: 'English',
  },
  {
    id: 5,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635029652/Book%20Home/Books/Best%20Selling/Food-of-the-Italian-South-by-Katie-Parla-300x456_wwdxqx.jpg',
    Title: 'Food of the Italian South',
    Author: 'KATIE PARLA',
    Price: '10.45',
    AuthorLink: 'katie-parla',
    Links: 'Food-of-the-Italian-South',
    Publisher: 'Clarkson Potter',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 256,
    Year: 2019,
    Language: 'English',
  },
  {
    id: 6,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635029663/Book%20Home/Books/Best%20Selling/Spy-A-Novel-by-Danielle-Steeel-300x456_ohnyld.jpg',
    Title: 'Spy: A Novel',
    Author: 'DANIELLE STEEL',
    Price: '20.00',
    OldPrice: '$21.0',
    AuthorLink: 'danielle-steel',
    Links: 'Spy:-A-Novel',
    Publisher: 'Ballantine Books',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 264,
    Year: 2007,
    Language: 'English',
  },
  {
    id: 7,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635030107/Book%20Home/Books/Best%20Selling/A-Lily-in-the-Light-by-Kristin-Fields-300x456_otemst.jpg',
    Title: 'A Lily in the Light',
    Author: 'KRISTIN FIELDS',
    Price: '34.00',
    AuthorLink: 'kristin-fields',
    Links: 'A-Lily-in-the-Light',
    Publisher: '	Lake Union Publishing',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 251,
    Year: 2018,
    Language: 'English',
  },
  {
    id: 8,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635029842/Book%20Home/Books/Best%20Selling/Invisible-Man-Ellison-Ralph-9780141184425_qkmafn.jpg',
    Title: 'Invicible Man',
    Author: 'Elison Ralph',
    Price: '24.65',
    AuthorLink: 'elison-ralph',
    Links: 'Invicible-Man',
    Publisher: 'Modern Library',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 251,
    Year: 1994,
    Language: 'English',
  },
  {
    id: 9,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635029643/Book%20Home/Books/Best%20Selling/2-Rules-for-Life-An-Antidote-to-Chaos-by-Jordan-B.-Peterson-300x456_lnpopl.jpg',
    Title: '12 Rules for Life: An Antidote to Chaos',
    Author: 'JORDAN B. PETERSON',
    Price: '12.43',
    OldPrice: '$15.0',
    AuthorLink: 'jordan-b-peterson',
    Links: '12-Rules-for-Life:-An-Antidote-to-Chaos',
    Publisher: '	Random House',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 409,
    Year: 2018,
    Language: 'English',
  },
  {
    id: 10,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635029900/Book%20Home/Books/Best%20Selling/9780425284704_ox2vhb.jpg',
    Title: 'Before We Were Yours',
    Author: 'Lisa Wingate',
    Price: '10.00',
    OldPrice: '$12.98',
    AuthorLink: 'lisa-wingate',
    Links: 'Before-We-Were-Yours',
    Publisher: 'Quercus',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 480,
    Year: 2018,
    Language: 'English',
  },
  {
    id: 11,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635062639/Book%20Home/Books/Latest%20Books/Children-of-Blood-and-Bone-Legacy-of-Orisha-by-Tomi-Adeyemi-300x456_sgo07q.jpg',
    Title: 'Children of Blood and Bone',
    Author: 'TOMI ADEYEMI',
    Price: '20.90',
    AuthorLink: 'tomi-adeyemi',
    Links: 'Children-of-Blood-and-Bone',
    Publisher: 'Henry Holt and Co',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 544,
    Year: 2018,
    Language: 'English',
  },
  {
    id: 12,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635062835/Book%20Home/Books/Latest%20Books/Magnolia-Table-A-Collection-of-Recipes-for-Gathering-by-Joanna-Gaines-300x456_ymcxud.jpg',
    Title: 'Magnolia Table',
    Author: 'JOANNA GAINES',
    Price: '15.87',
    OldPrice: '$20.00',
    AuthorLink: 'joanna-gaines',
    Links: 'Magnolia-Table',
    Publisher: 'William Morrow Cookbooks',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 321,
    Year: 2016,
    Language: 'English',
  },
  {
    id: 13,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635063491/Book%20Home/Books/Latest%20Books/The-Woman-in-the-Window-A-Novel-by-A.-J.-Finn-300x456_unfj4l.jpg',
    Title: 'The Woman in the Window',
    Author: 'A.J FINN',
    Price: '14.77',
    AuthorLink: 'a-j-finn',
    Links: 'The-Woman-in-the-Window',
    Publisher: 'Viking',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 448,
    Year: 2018,
    Language: 'English',
  },
  {
    id: 14,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635063854/Book%20Home/Books/Latest%20Books/Where-the-Crawdads-Sing-by-Delia-Owens-300x456_wz4hr9.jpg',
    Title: 'Where the Crawdads Sing',
    Author: 'Delia Owens',
    Price: '24.55',
    AuthorLink: 'delia-owens',
    Links: 'Where-the-Crawdads-Sing',
    Publisher: 'William Morrow Cookbooks',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 448,
    Year: 2018,
    Language: 'English',
  },
  {
    id: 15,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635064171/Book%20Home/Books/Latest%20Books/Wonder-R.-J.-Palacio-300x456_taf2n0.jpg',
    Title: 'Wonder',
    Author: 'R. J. PALACIO',
    Price: '17.90',
    OldPrice: '$20.79',
    AuthorLink: 'r-j-palacio',
    Links: 'Wonder',
    Publisher: '	Random House',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 316,
    Year: 2014,
    Language: 'English',
  },
  {
    id: 16,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635064305/Book%20Home/Books/Latest%20Books/Im-Fine-and-Neither-Are-You-by-Camille-Paga_CC_81n-300x456_egd5mv.jpg',
    Title: 'I’m Fine and Neither Are You',
    Author: 'CAMILLE PAGÁN',
    Price: '13.00',
    AuthorLink: 'camille-pagan',
    Links: 'I’m-Fine-and-Neither-Are-You',
    Publisher: 'Lake Union Publishing',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 270,
    Year: 2019,
    Language: 'English',
  },
  {
    id: 17,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635064546/Book%20Home/Books/Latest%20Books/Know-Why-the-Caged-Bird-Sings-by-Maya-Angelou-300x456_hz2jpg.jpg',
    Title: 'Know Why the Caged Bird Sings',
    Author: 'MAYA ANGELOU',
    Price: '19.00',
    OldPrice: '$21.00',
    AuthorLink: 'maya-angelou',
    Links: 'Know-Why-the-Caged-Bird-Sings',
    Publisher: 'Ballantine Books',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 304,
    Year: 2009,
    Language: 'English',
  },
  {
    id: 18,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635064745/Book%20Home/Books/Latest%20Books/The-Diary-of-a-Young-Girl-by-Anne-Frank-300x456_ifate1.jpg',
    Title: 'The Diary of a Young Girl',
    Author: 'ANNE FRANK',
    Price: '$18.00',
    OldPrice: '20.00',
    AuthorLink: 'anne-frank',
    Links: 'The-Diary-of-a-Young-Girl',
    Publisher: 'Bantam',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 283,
    Year: 1993,
    Language: 'English',
  },
  {
    id: 19,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635064837/Book%20Home/Books/Latest%20Books/The-Old-Drift-by-Namwali-Serpell-300x456_g4f5aq.jpg',
    Title: 'The Old Drift',
    Author: 'NAMWALI SERPELL',
    Price: '20.00',
    AuthorLink: 'namwali-serpell',
    Links: 'The-Old-Drift',
    Publisher: 'Hogarth',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 576,
    Year: 2019,
    Language: 'English',
  },
  {
    id: 20,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635064969/Book%20Home/Books/Latest%20Books/The-Tattooist-of-Auschwitz-by-Heather-Morris-300x456_dzeben.jpg',
    Title: 'The Tattooist of Auschwitz',
    Author: 'HEATHER MORRIS',
    Price: '15.00',
    OldPrice: '$16.50',
    AuthorLink: 'heather-morris',
    Links: 'The-Tattooist-of-Auschwitz',
    Publisher: 'Harper Paperbacks',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 288,
    Year: 2018,
    Language: 'English',
  },
]

export default Data
