const Data = [
  {
    id: 1,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635029952/Book%20Home/Books/Best%20Selling/The-Illustrated-a-Brief-History-of-Time-9780553103748_lhotvg.jpg',
    Title: 'A Brief History of Time',
    Author: 'Stephen Hawking',
    Price: '21.55',
    OldPrice: '$25.0',
    AuthorLink: 'stephen-hawking',
    Links: 'A-Brief-History-of-Time',
    Publisher: 'Bantam',
    Description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?`,
    Pages: 212,
    Year: 1998,
    Language: 'English',
    Test: [
      {
        id: 1,
        Fresh: 'What a test',
      },
      {
        id: 2,
        Fresh: 'What a testss',
      },
    ],
  },
  {
    id: 2,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635029991/Book%20Home/Books/Best%20Selling/The-Book-of-Night-Women-9781594488573_eyc4g9.jpg',
    Title: 'The Book of Night Women',
    Author: 'Marlon James',
    Price: '20.00',
    AuthorLink: 'marlon-james',
    Links: 'The-Book-of-Night-Women',
    Publisher: 'Penguin',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 427,
    Year: 2010,
    Language: 'English',
  },
  {
    id: 3,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635030176/Book%20Home/Books/Best%20Selling/Big-Week-The-Biggest-Air-Battle-of-World-War-II-by-James-Holland-300x456_g3meou.jpg',
    Title: 'The Biggest Air Battle of WWII',
    Author: 'James Holland',
    Price: '30.00',
    OldPrice: '$35.43',
    AuthorLink: 'james-holland',
    Links: 'The-Biggest-Air-Battle-of-WWII',
    Publisher: 'Atlantic Monthly Press',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 400,
    Year: 2018,
    Language: 'English',
  },
  {
    id: 4,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635029646/Book%20Home/Books/Best%20Selling/Waiting-for-Eden-A-novel-by-Elliot-Ackerman-300x456_pc7sqo.jpg',
    Title: 'Waiting for Eden: A Novel',
    Author: 'ELLIOT ACKERMAN',
    Price: '10.34',
    AuthorLink: 'elliot-ackerman',
    Links: 'Waiting-for-Eden:-A-Novel',
    Publisher: 'Knopf',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 192,
    Year: 2018,
    Language: 'English',
  },
  {
    id: 5,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635029652/Book%20Home/Books/Best%20Selling/Food-of-the-Italian-South-by-Katie-Parla-300x456_wwdxqx.jpg',
    Title: 'Food of the Italian South',
    Author: 'KATIE PARLA',
    Price: '10.45',
    AuthorLink: 'katie-parla',
    Links: 'Food-of-the-Italian-South',
    Publisher: 'Clarkson Potter',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 256,
    Year: 2019,
    Language: 'English',
  },
  {
    id: 6,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635029663/Book%20Home/Books/Best%20Selling/Spy-A-Novel-by-Danielle-Steeel-300x456_ohnyld.jpg',
    Title: 'Spy: A Novel',
    Author: 'DANIELLE STEEL',
    Price: '20.00',
    OldPrice: '$21.0',
    AuthorLink: 'danielle-steel',
    Links: 'Spy:-A-Novel',
    Publisher: 'Ballantine Books',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 264,
    Year: 2007,
    Language: 'English',
  },
  {
    id: 7,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635030107/Book%20Home/Books/Best%20Selling/A-Lily-in-the-Light-by-Kristin-Fields-300x456_otemst.jpg',
    Title: 'A Lily in the Light',
    Author: 'KRISTIN FIELDS',
    Price: '34.00',
    AuthorLink: 'kristin-fields',
    Links: 'A-Lily-in-the-Light',
    Publisher: '	Lake Union Publishing',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 251,
    Year: 2018,
    Language: 'English',
  },
  {
    id: 8,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635029842/Book%20Home/Books/Best%20Selling/Invisible-Man-Ellison-Ralph-9780141184425_qkmafn.jpg',
    Title: 'Invisible Man',
    Author: 'Elison Ralph',
    Price: '24.65',
    AuthorLink: 'elison-ralph',
    Links: 'Invisible-Man',
    Publisher: 'Modern Library',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 251,
    Year: 1994,
    Language: 'English',
  },
  {
    id: 9,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635029643/Book%20Home/Books/Best%20Selling/2-Rules-for-Life-An-Antidote-to-Chaos-by-Jordan-B.-Peterson-300x456_lnpopl.jpg',
    Title: '12 Rules for Life: An Antidote to Chaos',
    Author: 'JORDAN B. PETERSON',
    Price: '12.43',
    OldPrice: '$15.0',
    AuthorLink: 'jordan-b-peterson',
    Links: '12-Rules-for-Life:-An-Antidote-to-Chaos',
    Publisher: '	Random House',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 409,
    Year: 2018,
    Language: 'English',
  },
  {
    id: 10,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635029900/Book%20Home/Books/Best%20Selling/9780425284704_ox2vhb.jpg',
    Title: 'Before We Were Yours',
    Author: 'Lisa Wingate',
    Price: '10.00',
    OldPrice: '$12.98',
    AuthorLink: 'lisa-wingate',
    Links: 'Before-We-Were-Yours',
    Publisher: 'Quercus',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 480,
    Year: 2018,
    Language: 'English',
  },
  {
    id: 11,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635062639/Book%20Home/Books/Latest%20Books/Children-of-Blood-and-Bone-Legacy-of-Orisha-by-Tomi-Adeyemi-300x456_sgo07q.jpg',
    Title: 'Children of Blood and Bone',
    Author: 'TOMI ADEYEMI',
    Price: '20.90',
    AuthorLink: 'tomi-adeyemi',
    Links: 'Children-of-Blood-and-Bone',
    Publisher: 'Henry Holt and Co',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 544,
    Year: 2018,
    Language: 'English',
  },
  {
    id: 12,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635062835/Book%20Home/Books/Latest%20Books/Magnolia-Table-A-Collection-of-Recipes-for-Gathering-by-Joanna-Gaines-300x456_ymcxud.jpg',
    Title: 'Magnolia Table',
    Author: 'JOANNA GAINES',
    Price: '15.87',
    OldPrice: '$20.00',
    AuthorLink: 'joanna-gaines',
    Links: 'Magnolia-Table',
    Publisher: 'William Morrow Cookbooks',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 321,
    Year: 2016,
    Language: 'English',
  },
  {
    id: 13,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635063491/Book%20Home/Books/Latest%20Books/The-Woman-in-the-Window-A-Novel-by-A.-J.-Finn-300x456_unfj4l.jpg',
    Title: 'The Woman in the Window',
    Author: 'A.J FINN',
    Price: '14.77',
    AuthorLink: 'a-j-finn',
    Links: 'The-Woman-in-the-Window',
    Publisher: 'Viking',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 448,
    Year: 2018,
    Language: 'English',
  },
  {
    id: 14,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635063854/Book%20Home/Books/Latest%20Books/Where-the-Crawdads-Sing-by-Delia-Owens-300x456_wz4hr9.jpg',
    Title: 'Where the Crawdads Sing',
    Author: 'Delia Owens',
    Price: '24.55',
    AuthorLink: 'delia-owens',
    Links: 'Where-the-Crawdads-Sing',
    Publisher: 'William Morrow Cookbooks',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 448,
    Year: 2018,
    Language: 'English',
  },
  {
    id: 15,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635064171/Book%20Home/Books/Latest%20Books/Wonder-R.-J.-Palacio-300x456_taf2n0.jpg',
    Title: 'Wonder',
    Author: 'R. J. PALACIO',
    Price: '17.90',
    OldPrice: '$20.79',
    AuthorLink: 'r-j-palacio',
    Links: 'Wonder',
    Publisher: '	Random House',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 316,
    Year: 2014,
    Language: 'English',
  },
  {
    id: 16,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635064305/Book%20Home/Books/Latest%20Books/Im-Fine-and-Neither-Are-You-by-Camille-Paga_CC_81n-300x456_egd5mv.jpg',
    Title: 'I’m Fine and Neither Are You',
    Author: 'CAMILLE PAGÁN',
    Price: '13.00',
    AuthorLink: 'camille-pagan',
    Links: 'I’m-Fine-and-Neither-Are-You',
    Publisher: 'Lake Union Publishing',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 270,
    Year: 2019,
    Language: 'English',
  },
  {
    id: 17,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635064546/Book%20Home/Books/Latest%20Books/Know-Why-the-Caged-Bird-Sings-by-Maya-Angelou-300x456_hz2jpg.jpg',
    Title: 'Know Why the Caged Bird Sings',
    Author: 'MAYA ANGELOU',
    Price: '19.00',
    OldPrice: '$21.00',
    AuthorLink: 'maya-angelou',
    Links: 'Know-Why-the-Caged-Bird-Sings',
    Publisher: 'Ballantine Books',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 304,
    Year: 2009,
    Language: 'English',
  },
  {
    id: 18,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635064745/Book%20Home/Books/Latest%20Books/The-Diary-of-a-Young-Girl-by-Anne-Frank-300x456_ifate1.jpg',
    Title: 'The Diary of a Young Girl',
    Author: 'ANNE FRANK',
    Price: '18.00',
    OldPrice: '$20.00',
    AuthorLink: 'anne-frank',
    Links: 'The-Diary-of-a-Young-Girl',
    Publisher: 'Bantam',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 283,
    Year: 1993,
    Language: 'English',
  },
  {
    id: 19,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635064837/Book%20Home/Books/Latest%20Books/The-Old-Drift-by-Namwali-Serpell-300x456_g4f5aq.jpg',
    Title: 'The Old Drift',
    Author: 'NAMWALI SERPELL',
    Price: '20.00',
    AuthorLink: 'namwali-serpell',
    Links: 'The-Old-Drift',
    Publisher: 'Hogarth',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 576,
    Year: 2019,
    Language: 'English',
  },
  {
    id: 20,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635064969/Book%20Home/Books/Latest%20Books/The-Tattooist-of-Auschwitz-by-Heather-Morris-300x456_dzeben.jpg',
    Title: 'The Tattooist of Auschwitz',
    Author: 'HEATHER MORRIS',
    Price: '15.00',
    OldPrice: '$16.50',
    AuthorLink: 'heather-morris',
    Links: 'The-Tattooist-of-Auschwitz',
    Publisher: 'Harper Paperbacks',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 288,
    Year: 2018,
    Language: 'English',
  },
  {
    id: 21,
    Title: 'Ugly Love',
    Author: 'Colleen Hoover',
    AuthorLink: 'colleen-hoover',
    Links: 'Ugly-Love',
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635284826/Book%20Home/Books/Special%20Offers/eba501594ab62859df0601e626eb7631_qlymbe.jpg',
    OldPrice: '$30',
    Price: 25,
    Publisher: 'Atria Books',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 337,
    Year: 2014,
    Language: 'English',
  },
  {
    id: 22,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635281326/Book%20Home/Books/Special%20Offers/Lost-and-Found-A-Novel-Hardcover-by-Danielle-Steel-600x913_bvfjd2.jpg',
    Title: 'Lost and Found: A Novel',
    Author: 'DANIELLE STEEL',
    Price: '20.00',
    OldPrice: '$21.0',
    AuthorLink: 'danielle-steel',
    Links: 'Lost-and-Found:-A-Novel',
    Publisher: 'Ballantine Books',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 350,
    Year: 2019,
    Language: 'English',
  },
  {
    id: 23,
    Title: 'The Feather Thief',
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635281936/Book%20Home/Books/Special%20Offers/The-Feather-Thief-by-Kirk-Wallace-Johnson-600x906_tk7vmr.jpg',
    Author: 'Kirk Wallace Johnson',
    Price: '18.00',
    OldPrice: '$26.0',
    AuthorLink: 'kirk-wallace-johnson',
    Links: 'The-Feather-Thief',
    Publisher: 'Disney-Hyperion',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 212,
    Year: 2018,
    Language: 'English',
  },
  {
    id: 24,
    Title: 'Becoming',
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635283992/Book%20Home/Books/Special%20Offers/Becoming-by-Michelle-Obama-600x912_pzxqsv.jpg',
    Price: '35.00',
    OldPrice: '$40.00',
    Author: 'Michelle Obama',
    AuthorLink: 'michelle-obama',
    Links: 'Becoming',
    Publisher: 'Viking',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 448,
    Year: 2018,
    Language: 'English',
  },
  {
    id: 25,
    Title: 'The Invisible Life of Addie LaRue',
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635284514/Book%20Home/Books/Special%20Offers/054045f48d75d227d92c8dfa6f03ed15_fuxabj.png',
    Price: '35.00',
    OldPrice: '$40.00',
    Author: 'V. E. Schwab',
    AuthorLink: 'V-E-Schwab',
    Links: 'The-Invisible-Life-of-Addie-LaRue',
    Publisher: 'Tor Books',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 448,
    Year: 2020,
    Language: 'English',
  },
  {
    id: 26,
    Title: 'Black Leopard, Red Wolf (The Dark Star Trilogy)',
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635312052/Book%20Home/Books/Special%20Offers/Black-Leopard-Red-Wolf-The-Dark-Star-Trilogy-by-Marlon-James-600x912_quo64c.jpg',
    Price: '15.00',
    OldPrice: '$20.00',
    Author: 'Marlon James',
    AuthorLink: 'marlon-james',
    Links: 'Black-Leopard-Red-Wolf-(The-Dark-Star-Trilogy)',
    Publisher: 'Riverhead Books',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 640,
    Year: 2019,
    Language: 'English',
  },
  {
    id: 27,
    Title: 'Tell Me A Story: 250 Great Books for Kids',
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635321853/Book%20Home/Books/Children%20Books/2dbe8e8732355553103e881ef63efeac_ezwtjw.jpg',
    Price: '45.00',
    OldPrice: '$51.00',
    Author: 'Sandford, Grace',
    AuthorLink: 'sandford-grace',
    Links: 'Tell-Me-A-Story:-250-Great-Books-for-Kids',
    Publisher: 'Team Sandford',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 416,
    Year: 2016,
    Language: 'English',
  },
  {
    id: 28,
    Title: 'The Cat in the Hat Book and Jigsaw Pack',
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635320103/Book%20Home/Books/Children%20Books/632f1c34075b5fb3a14dc8a94587f2d3_mkwryy.jpg',
    Price: '16.00',
    OldPrice: '$20.00',
    Author: 'Dr. Seuss',
    AuthorLink: 'dr-seuss',
    Links: 'The-Cat-in-the-Hat-Book-and-Jigsaw-Pack',
    Publisher: 'Random House Children’s Books',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 64,
    Year: 1970,
    Language: 'English',
  },
  {
    id: 29,
    Title: 'Frozen Junior Novel',
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635322133/Book%20Home/Books/Children%20Books/cedc17b711d458a3e4740f419efc7646_e2mfrr.jpg',
    Price: '26.00',
    Author: 'Disney Book Group',
    AuthorLink: 'disney-book-group',
    Links: 'Frozen-Junior-Novel',
    Publisher: 'Disney Electronic Content',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 64,
    Year: 2021,
    Language: 'English',
  },
  {
    id: 30,
    Title: 'Fantastic Mr. Fox',
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635322885/Book%20Home/Books/Children%20Books/113eca31ee7e25a3865d1623d730aa57_swpiyp.jpg',
    Price: '21.00',
    Author: 'Dahl Roald',
    AuthorLink: 'dahl-roald',
    Links: 'Fantastic-Mr-Fox',
    Publisher: 'Puffin',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: '96 / 41',
    Year: 1988,
    Language: 'English',
  },
  {
    id: 31,
    Title:
      'The political economy of Stalinism: evidence from the Soviet secret archives',
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635373330/Book%20Home/Books/Biography%20Books/cbefaeb3bdfc32dac11fecaf7802bcbe_a60kci.jpg',
    Price: '32.00',
    Author: 'Paul R. Gregory',
    AuthorLink: 'paul-r-gregory',
    Links:
      'The-political-economy-of Stalinism:-evidence-from-the-Soviet-secret-archives',
    Publisher: 'Cambridge University Press',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 321,
    Year: 2004,
    Language: 'English',
  },
  {
    id: 32,
    Title: 'Ain’t I a Woman: Black Women and Feminism',
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635373645/Book%20Home/Books/Biography%20Books/39b2db66836139d6193b1af46494d3bc_eiuvgi.jpg',
    Price: '25.00',
    Author: 'Bell Hooks',
    AuthorLink: 'bell-hooks',
    Links: 'Ain’t-I-a-Woman:-Black-Women-and-Feminism',
    Publisher: 'Routledge',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 205,
    Year: 2014,
    Language: 'English',
  },
  {
    id: 33,
    Title: 'Hitler A Biography',
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635376171/Book%20Home/Books/Biography%20Books/32f840078ba820d154085340101c787f_fb143k.jpg',
    Price: '25.00',
    Author: 'Ian Kershaw',
    AuthorLink: 'ian-kershaw',
    Links: 'Hitler-A-Biography',
    Publisher: 'W. W. Norton & Company',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 488,
    Year: 2010,
    Language: 'English',
  },
  {
    id: 34,
    Title: 'Einstein: His Life and Universe',
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635376446/Book%20Home/Books/Biography%20Books/edceb4c90267dfdbd47cd6f781d1b141_gditr9.jpg',
    Price: '25.00',
    Author: 'Walter Isaacson',
    AuthorLink: 'walter-isaacson',
    Links: 'Einstein:-His-Life-and-Universe',
    Publisher: 'Simon & Schuster',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 704,
    Year: 2007,
    Language: 'English',
  },
  {
    id: 35,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635463168/Book%20Home/Books/Authors/Danielle-steel/Blessing-in-Disguise-A-Novel-by-Danielle-Steel-300x456_xbe1lj.jpg',
    Title: 'Blessing in Disguise: A Novel',
    Author: 'DANIELLE STEEL',
    Price: '20.00',
    AuthorLink: 'danielle-steel',
    Links: 'Blessing-in-Disguise:-A-Novel',
    Publisher: 'Ballantine Books',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 256,
    Year: 1994,
    Language: 'English',
  },
  {
    id: 36,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635463176/Book%20Home/Books/Authors/Danielle-steel/Silent-Night-A-Novel-by-Danielle-Steel-300x456_p3udqb.jpg',
    Title: 'Silent Night: A Novel',
    Author: 'DANIELLE STEEL',
    Price: '27.50',
    OldPrice: '$34.67',
    AuthorLink: 'danielle-steel',
    Links: 'Silent-Night:-A-Novel',
    Publisher: 'Ballantine Books',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 270,
    Year: 2019,
    Language: 'English',
  },
  {
    id: 37,
    Title: `Pete's Dragon Junior Novel`,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635551852/Book%20Home/Books/Top%20Books/9781484749920_xaxgaf.jpg',
    Price: '34.00',
    Author: 'Disney Book Group',
    AuthorLink: 'disney-book-group',
    Links: `Pete's-Dragon-Junior-Novel`,
    Publisher: 'Disney Electronic Content',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 64,
    Year: 2016,
    Language: 'English',
  },
  {
    id: 38,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635552260/Book%20Home/Books/Top%20Books/Letter-to-My-Daughter-Angelou-Maya-9780812980035_iuxsmy.jpg',
    Title: 'Letter to My Daughter',
    Author: 'Maya Angelou',
    Price: '19.00',
    OldPrice: '$21.00',
    AuthorLink: 'maya-angelou',
    Links: 'Letter-to-My-Daughter',
    Publisher: '	Random House',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 166,
    Year: 2009,
    Language: 'English',
  },
  {
    id: 39,
    Title: 'All Your Perfects: A Novel',
    Author: 'Colleen Hoover',
    AuthorLink: 'colleen-hoover',
    Links: 'All-Your-Perfects:-A-Novel',
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635553625/Book%20Home/Books/Top%20Books/9781501171598_djtfhj.jpg',
    OldPrice: '$30',
    Price: 25,
    Publisher: 'Atria Books',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 337,
    Year: 2018,
    Language: 'English',
  },
  {
    id: 40,
    Title: `John Crow's Devil`,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635553765/Book%20Home/Books/Top%20Books/9781780748498_cqcxc5.jpg',
    Price: '15.00',
    OldPrice: '$20.00',
    Author: 'Marlon James',
    AuthorLink: 'marlon-james',
    Links: `John-Crow's-Devil`,
    Publisher: '	Oneworld Publications,',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 640,
    Year: 2019,
    Language: 'English',
  },
  {
    id: 41,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635555829/Book%20Home/Books/Top%20Books/9781101947371_nubfqn.jpg',
    Title: 'Dark at the Crossing: A novel',
    Author: 'ELLIOT ACKERMAN',
    Price: '10.34',
    AuthorLink: 'elliot-ackerman',
    Links: 'Dark-at-the-Crossing:-A-novel',
    Publisher: 'Knopf',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 192,
    Year: 2017,
    Language: 'English',
  },
  {
    id: 42,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635555978/Book%20Home/Books/Top%20Books/The-Battle-of-Britain-Holland-James-9780593059135_lokr5l.jpg',
    Title: 'The Battle of Britain',
    Author: 'James Holland',
    Price: '30.00',
    OldPrice: '$35.43',
    AuthorLink: 'james-holland',
    Links: 'The-Battle-of-Britain',
    Publisher: '	Transworld Publishers',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 400,
    Year: 2010,
    Language: 'English',
  },
  {
    id: 43,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635556091/Book%20Home/Books/Top%20Books/Wildwood-Creek-Wingate-Lisa-9780764208249_zd9fb9.jpg',
    Title: 'Wildwood Creek',
    Author: 'Lisa Wingate',
    Price: '10.00',
    OldPrice: '$12.98',
    AuthorLink: 'lisa-wingate',
    Links: 'Wildwood-Creek',
    Publisher: 'QuBethany House Publishersercus',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 384,
    Year: 2014,
    Language: 'English',
  },
  {
    id: 44,
    Title: `Inside Out - Driven by Emotions`,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635556233/Book%20Home/Books/Top%20Books/9781484722039_zq9lf8.jpg',
    Price: '34.00',
    Author: 'Disney Book Group',
    AuthorLink: 'disney-book-group',
    Links: `Inside-Out-Driven-by-Emotions`,
    Publisher: 'Disney Electronic Content',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 64,
    Year: 2015,
    Language: 'English',
  },
  {
    id: 45,
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635556403/Book%20Home/Books/Top%20Books/9780804187183_np1qb7.jpg',
    Title: 'Tasting Rome',
    Author: 'KATIE PARLA',
    Price: '10.45',
    AuthorLink: 'katie-parla',
    Links: 'Tasting-Rome',
    Publisher: 'Clarkson Potter',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 256,
    Year: 2016,
    Language: 'English',
  },
  {
    id: 46,
    Title: 'Yertle the Turtle and Other Stories',
    Image:
      'https://res.cloudinary.com/osaz/image/upload/v1635556526/Book%20Home/Books/Top%20Books/Yertle-the-Turtle-and-Other-Stories-Dr-Seuss-9780375844843_sus7nz.jpg',
    Price: '16.00',
    OldPrice: '$20.00',
    Author: 'Dr. Seuss',
    AuthorLink: 'dr-seuss',
    Links: 'Yertle-the-Turtle-and-Other-Stories',
    Publisher: 'Random House Children’s Books',
    Description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam quis consectetur culpa facilis aliquid fugit nihil libero laborum repudiandae voluptates? Placeat vel deleniti in praesentium obcaecati ex impedit voluptas mollitia?',
    Pages: 64,
    Year: 1970,
    Language: 'English',
  },
]

export default Data
